sprints:
######
# Simplest config
# only mandatory arguments
######
    my_project_sprint_1: # this is the name you'll specify when running any command
        commited_man_days: 30
        zebra:
            client_id: 111 # integer, zebra client id
            activities: '*' # can be either '*' (all activities) or a list of activity ids [1,2,3]
            users: '*' # can be either '*' (all users) or a list of zebra users id [1,2,3]
            start_date : 2012-11-19 # date format yyyy-mm-dd
            end_date : 2012-12-10 # date format yyyy-mm-dd
        jira:
            project_id: 12345 # Run `lst jira-config-helper jlc-100` to get its project id (change jlc-100 by the id of a story in your current sprint)
            sprint_name: "Fix+Version+As+Specified+In+Jira" # as seen in jira query builder (usually blanks are to be replaced with + in jira). Run `lst jira-config-helper jlc-100` to get its sprint name (replace jlc-100 by the id of a story in your current sprint)


######
# Advanced config
# all optional arguments below can be completely deleted if not used
######
    my_project_sprint_2: # this is the name you'll specify when running any command
        commited_man_days: 30
        zebra:
            client_id: 111 # integer, zebra client id
            activities: '*' # can be either '*' (all activities) or a list of activity ids [1,2,3]
            users: [100,101,102] # can be either '*' (all users) or a list of zebra users id [1,2,3]
            start_date : 2012-11-19 # date format yyyy-mm-dd
            end_date : 2012-12-10 # date format yyyy-mm-dd
            force: # optional, use it to (force/)correct zebra values (this will not change the values *in* zebra, just force them to be displayed as you wish)
              - date: 2012-11-19 # can be either a single date...
                time: 8 # nb of hours. Can be either a number (= force value to 8 hours)...
              - date: [2013-04-09,2013-04-11] # ...or multiple dates (list)
                time: '+8' # ...or a delta string (to be added to the existing zebra value)...
              - date: '2013-04-09/2013-04-11' # ...or a date range (str separated by /)
                time: '-8' # ...in both directions
            planned: # optional, use it to display your MD consumption forecast on your burnup chart
              - date: 2012-11-19 # can be either a single date...
                time: 16 # nb of hours
              - date: [2013-04-09,2013-04-11] # ...or multiple dates (list)
                time: 24
              - date: '2013-04-09/2013-04-11' # ...or a date range (str separated by /)
                time: 24
        jira:
            project_id: 12345 # Run `lst jira-config-helper jlc-100` to get its project id (change jlc-100 by the id of a story in your current sprint
            sprint_name: "Fix+Version+As+Specified+In+Jira" # as seen in jira query builder (usually blanks are to be replaced with + in jira). Run `lst jira-config-helper jlc-100` to get its sprint name (replace jlc-100 by the id of a story in your current sprint
            nice_identifier: "(NICE)" # optional, how you specify that a story is a nice to have (must be part of the story title)
            closed_statuses:
                {6: closed, 10008: For PO Review} # optional, what status you consider as 'closed' (used to check if a story is "closed" and to know on what date it was closed reading the story activity stream)
            ignored: ['XXX-501', 'XXX-505'] # optional, list of stories that should be ignored
