zebra:
    url: "https://zebra.liip.ch"
    username: your_user_name
    password: your_password
jira:
    url: "https://jira.liip.ch"
    username: your_user_name
    password: your_password

# absolute path to an existing directory on your machine
# must be writable
output_dir: /home/user/my_graphs
